# -*- coding: utf-8 -*-
"""memes_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hDrHmIMByRTwBrATUXOA5NLk4YbM0PKJ
"""

import requests
from bs4 import BeautifulSoup
import json
import csv
#filecsv = open('meme.csv', 'w', encoding='utf8')
# Set the URL you want to webscrape from
url = 'https://imgflip.com/?page='
file = open('meme.json', 'w', encoding='utf8')
file.write('[\n')
data = {}
for page in range(20):
    print('------', page, '------')
    r = requests.get(url + str(page))
    print(url + str(page))
    soup = BeautifulSoup(r.content, "html.parser")
    ancher = soup.find_all( 'div', {'class': "base-unit clearfix"})
    i = 0
    for pt in ancher:
        img = pt.find('img', {'class': 'base-img'})
        if img:
            data['img'] = img['src']
            json_data = json.dumps(data, ensure_ascii=False)
            file.write(json_data)
            file.write(",\n")
file.write("\n]")
file.close()